name: Publish 
on:
  push:
    branches: [ "develop" ]
    # for possible necessary rebuilds 
    workflow_dispatch: 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo 
      uses: actions/checkout@v2
    - name: Install node
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Install antora 
      run: npm i antora 
    - name: Build 
      run: npx antora --fetch antora-playbook.yml
    - name: Publish to GH Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: build/site
